"""empty message

Revision ID: 462178bb983d
Revises: 740687619ea7
Create Date: 2024-07-18 15:04:46.712792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462178bb983d'
down_revision = '740687619ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropbox_url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('dropbox_url')

    # ### end Alembic commands ###
