"""empty message

Revision ID: 740687619ea7
Revises: b112b72d0e5b
Create Date: 2024-07-18 14:55:46.949864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740687619ea7'
down_revision = 'b112b72d0e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)

    # ### end Alembic commands ###
